
Spawn:
  #Place in which a player is teleported to after falling into the void.
  X: 0.0
  Y: 100.0
  Z: 0.0
  YAW: 90
  PITCH: 0
  WORLD: "world"
  EnabledWorlds:
    #List of worlds where VoidTP works.
    - "world"
    - "hub"
    - "spawn"


Scoreboard:
  Lines:
    - "Ello There"
    - "&bSup"
    - "&cChange this"
    - "&bFirecraft"
    - "&cNice"

Join:
  Messages:
    MOTD:
      - "&b================="
      - "&cWelcome &r%player_name%"
      - "&b================="
    StaffMOTD:
      - "&b================="
      - "&c Sup Staff Member"
      - "&c================="

    StaffJoinMessage: "&cA staff member has joined the server!"
    PlayerJoinMessage: "&bA player has joined the server!"
  GameMode: "SURVIVAL"
  ClearInventory: false
  TeleportToSpawn: true


FirstJoin:
  Messages:
    MOTD:
      - "&b================="
      - "&cWelcome &r%player_name%"
      - "&b================="

    PlayerJoinMessage: "&c%player_name% has joined us for the first time!"
  GameMode: "SURVIVAL"
  TeleportToSpawn: true
  ClearInventory: false
  Items:
    - "DIAMOND_SWORD;&bStarter Sword;4;&cStarter sword for, &cyour journey.;1"
    - "COOKED_BEEF;&bStarter Food;4;&cStarter food for, &cyour journey.;16"


Leave:
  Messages:
    PlayerLeaveMessage: "&e%player_name% has left the server."