VoidTeleport:
  #Void teleport settings
  Spawn:
    #Place in which a player is teleported to after falling into the void.
    X: 0.0
    Y: 100.0
    Z: 0.0
    YAW: 90
    PITCH: 0
    WORLD: "world"
  EnabledWorlds:
    #List of worlds where VoidTP works.
    - "world"
    - "hub"
    - "spawn"


Scoreboard:
  Lines:
    - ""
    - ""
    - ""
    - ""
    - ""

Join:
  Messages:
    MOTD:
      - ""
      - ""
      - ""
    StaffMOTD:
      - ""
      - ""
      - ""

    StaffJoinMessage: ""
    PlayerJoinMessage: ""
  GameMode: "SURVIVAL"
  ClearInventory: false
  TeleportToSpawn: true

Leave:
  Messages:
    PlayerLeaveMessage:
      - ""