Spawn:
  #Place in which a player is teleported to after falling into the void.
  X: 0.0
  Y: 100.0
  Z: 0.0
  YAW: 90
  PITCH: 0
  WORLD: "world"
  EnabledWorlds:
    #List of worlds where VoidTP works.
    - "world"
    - "hub"
    - "spawn"


Scoreboard:
  Lines:
    - "Ello There"
    - "&bSup"
    - "&cChange this"
    - "&bFirecraft"
    - "&cNice"

Join:
  Messages:
    MOTD:
      - "&b================="
      - "&cWelcome &r%player_name%"
      - "&b================="
    StaffMOTD:
      - "&b================="
      - "&c Sup Staff Member"
      - "&c================="

    StaffJoinMessage: "&cA staff member has joined the server!"
    PlayerJoinMessage: "&bA player has joined the server!"
  GameMode: "SURVIVAL"
  ClearInventory: false
  TeleportToSpawn: true
  Items:
    - "NETHER_STAR;&bServer Selector;4;&eOpen the server selector;1"


FirstJoin:
  Messages:
    MOTD:
      - "&b================="
      - "&cWelcome &r%player_name%"
      - "&b================="

    PlayerJoinMessage: "&c%player_name% has joined us for the first time!"
  GameMode: "SURVIVAL"
  TeleportToSpawn: true
  ClearInventory: false
  Items:
    - "DIAMOND_SWORD;&bStarter Sword;7;&cStarter sword for, &cyour journey.;1"
    - "NETHER_STAR;&bServer Selector;4;&eOpen the server selector;1"


Leave:
  Messages:
    PlayerLeaveMessage: "&e%player_name% has left the server."

ClickEvents:
  Items:
    - "&bServer Selector;open games"

GUIS:
  GameSelector:
    Opener: "games"
    Size: 54
    Title: "&bServer Menu"
    Items:
      - "&espawn;GRASS_BLOCK;20;&aTeleport to spawn!"
      - "&eDoubles;STONE_SWORD;24;&cComing Soon!"
    ClickEvents:
      - "20;spawn"
      - "24;help"